name: flutter_firebase_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.0.0
  cloud_firestore: ^3.1.4
  equatable: ^2.0.3
  firebase_core: ^1.10.5
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  meta: ^1.3.0
  shared_preferences_web: ^2.0.4
  very_good_analysis: ^2.3.0

dev_dependencies:
  bloc_test: ^8.0.0
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
